import { useCheckoutStore } from '@/store/useCheckoutStore.ts'
import type { EcwidProduct } from '@/types/ecwid'

const cartStore = useCheckoutStore()

export function addToCart(product: EcwidProduct): void {
  cartStore.addItem({
    id: product.id,
    title: product.name,
    price: product.price,
    imageURL: product.originalImageUrl,
    quantity: 1,
    slug: product.autogeneratedSlug,
  })
}
