import type { EcwidProduct, ProductCardItem } from '@/types/ecwid'

export function parseProductCards(rawProducts: EcwidProduct[]): ProductCardItem[] {
  return rawProducts.map((product) => {
    const formattedDiscount =
      product.compareToPrice && product.compareToPrice > product.price
        ? formatPrice(product.compareToPrice)
        : undefined

    return {
      title: product.name,
      price: formatPrice(product.price),
      discountedPrice: formattedDiscount,
      shortDescription: extractShortDescription(product.description),
      imageURL: product.originalImageUrl || '',
      slug: product.autogeneratedSlug,
      sku: product.sku,
      currentProduct: product,
    }
  })
}

function formatPrice(price: number): string {
  return `€ ${price}`
}

function extractShortDescription(html: string): string {
  const div = document.createElement('div')
  div.innerHTML = html
  return div.textContent?.slice(0, 120) || ''
}
