import type { EcwidProduct } from '@/types/ecwid';
import type { ProductCardItem } from '@/types/productCard';

// TODO: refactor to defaultFormattedPrice
export function parseProductCards(rawProducts: EcwidProduct[]): ProductCardItem[] {
  return rawProducts.map((product) => {
    const formattedDiscount =
      product.compareToPrice && product.compareToPrice > product.price
        ? formatPrice(product.compareToPrice)
        : undefined;

    return {
      title: product.name,
      price: formatPrice(product.price),
      discountedPrice: formattedDiscount,
      description: product.description,
      imageURL: product.originalImageUrl || '',
      slug: product.autogeneratedSlug,
      sku: product.sku,
      currentProduct: product,
    };
  });
}

function formatPrice(price: number): string {
  return `€ ${price}`;
}
