import type { EcwidProduct } from '@/types/ecwid';
import type { ProductCardItem } from '@/types/productCard';

export function parseProductCards(rawProducts: EcwidProduct[]): ProductCardItem[] {
  return rawProducts.map((product) => {
    return {
      title: product.name,
      price: product.defaultDisplayedPriceFormatted,
      discountedPrice: product.defaultDisplayedLowestPriceFormatted,
      description: product.description,
      imageURL: product.originalImageUrl || '',
      slug: product.autogeneratedSlug,
      sku: product.sku,
      currentProduct: product,
    };
  });
}
