<script setup lang="ts">
import { onMounted, watch } from 'vue';
import { useCategoryStore } from '@/stores/useCategoryStore';
import CategoryCard from '@/components/CategoryPage/CategoryCard.vue';
import BreadCrumbs from '@/components/CategoryPage/BreadCrumbs.vue';
import ProductCard from '@/components/CategoryPage/ProductCard.vue';
import { useRoute } from 'vue-router';
import { useProductStore } from '@/stores/useProductStore';
import ProductCardSkeleton from '@/components/CategoryPage/ProductCardSkeleton.vue';
import CategoryCardSkeleton from '@/components/CategoryPage/CategoryCardSkeleton.vue';

const categoryStore = useCategoryStore();
const productStore = useProductStore();

const route = useRoute();

watch(
  () => route.params.categorySlug,
  async (newSlug) => {
    document.title = categoryStore.getCategoryNameBySlug(newSlug as string);
    categoryStore.categories = categoryStore.getCategoriesBySlug(newSlug as string) ?? [];
    await productStore.loadProducts(newSlug as string);
  },
);

onMounted(async () => {
  await categoryStore.loadCategories();
  if (route.params.categorySlug) {
    document.title = categoryStore.getCategoryNameBySlug(route.params.categorySlug as string);
    categoryStore.categories =
      categoryStore.getCategoriesBySlug(route.params.categorySlug as string) ?? [];
  }
  await productStore.loadProducts(route.params.categorySlug as string);
});
</script>

<template>
  <h1 class="text-center text-2xl font-bold mb-4">Catalog</h1>
  <div class="catalog-main-breadcrumbs">
    <BreadCrumbs />
  </div>
  <div class="category-list">
    <template v-if="categoryStore.loading">
      <CategoryCardSkeleton v-for="n in 2" :key="n" />
    </template>
    <CategoryCard
      v-for="category in categoryStore.categories"
      :key="category.id"
      :image="category.image || ''"
      :name="category.name"
      :slug="category.autogeneratedSlug"
    />
  </div>
  <div class="catalog-main-product-list">
    <template v-if="categoryStore.loading || productStore.loading">
      <ProductCardSkeleton v-for="n in 9" :key="n" />
    </template>
    <ProductCard
      v-for="(product, index) in productStore.currentPageProducts"
      :key="index"
      :product="product"
    />
  </div>
</template>

<style scoped>
.category-list {
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
  justify-content: center;
}
.catalog-main-product-list {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  justify-content: center;
  margin-top: 1.5rem;
  align-items: stretch;
}
.catalog-main-breadcrumbs {
  width: 100%;
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-wrap: wrap;
}
</style>
