<script setup lang="ts">
import Button from 'primevue/button'
import { useCategories } from '@/services/categoryService'
import { onMounted, watch } from 'vue'
import { useCategoryStore } from '@/store/useCategoryStore'
import CategoryCard from '@/components/CategoryPage/CategoryCard.vue'
import BreadCrumbs from '@/components/CategoryPage/BreadCrumbs.vue'
import { useRoute } from 'vue-router'

const { fetchCategories } = useCategories()
const categoryStore = useCategoryStore()

const route = useRoute()

watch(
  () => route.params.categorySlug,
  (newSlug) => {
    categoryStore.categories = categoryStore.getCategoriesByParentId(newSlug as string) ?? [] // maybe search by slug?
  },
)

onMounted(async () => {
  await categoryStore.loadCategories()
})
</script>

<template>
  <main>
    <BreadCrumbs />
    <div class="category-list">
      <CategoryCard
        v-for="category in categoryStore.categories"
        :key="category.id"
        :image="category.image || ''"
        :name="category.name"
        :slug="category.autogeneratedSlug"
      />
    </div>
    <Button
      label="Fetch Categories"
      outlined
      severity="secondary"
      @click="fetchCategories(173495753)"
    />
    <Button
      label="All Categories"
      outlined
      severity="secondary"
      @click="console.log(categoryStore.allCategories)"
    />
  </main>
</template>

<style scoped>
.category-list {
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
  justify-content: center;
}
</style>
