<script setup lang="ts">
import ProductPage from '@/components/ProductPage/ProductPageComponent.vue'
//import router from '@/router';
import { useProductStore } from '@/store/useProductStore'
import { onMounted, watch } from 'vue'
import { useRoute } from 'vue-router'

const productStore = useProductStore()
const route = useRoute()

watch(
  () => route.params.productSlug,
  async (newSlug) => {
    await productStore.loadProductBySlug(newSlug as string)
    if (!productStore.currentProduct) {
      //router.push('/404')
    }
  },
)

onMounted(async () => {
  await productStore.loadProductBySlug(route.params.productSlug as string)
  if (!productStore.currentProduct) {
    //router.push('/404')
  }
})
</script>

<template>
  <main>
    <ProductPage
      :image="
        productStore.currentProduct?.originalImageUrl ||
        'https://d2j6dbq0eux0bg.cloudfront.net/default-store/apparel/3051759298.jpg'
      "
      :name="productStore.currentProduct?.name || 'Loading...'"
      :slug="productStore.currentProduct?.autogeneratedSlug || 'sample-product'"
      :price="productStore.currentProduct?.defaultDisplayedPriceFormatted || '19.99'"
      :description="
        productStore.currentProduct?.description || 'This is a sample product description.'
      "
      :loading="productStore.loading"
    />
  </main>
</template>
