export interface EcwidCategory {
  id: number
  orderBy: number
  name: string
  nameTranslated: Record<string, string>
  url: string
  parentId: number | null
  autogeneratedSlug: string
  customSlug: string
  productCount: number
  description: string
  descriptionTranslated: Record<string, string>
  enabled: boolean
  isSampleCategory: boolean
  seoTitle: string
  seoDescription: string
  image: string | undefined
  alt: {
    main: string
  }
}

export interface EcwidCategoriesResponse {
  total: number
  count: number
  offset: number
  limit: number
  items: EcwidCategory[]
}

export interface ProductCardItem {
  title: string
  price: string
  discountedPrice?: string | null
  shortDescription: string
  imageURL: string
  slug: string
  sku: string
  currentProduct: EcwidProduct
}

export interface EcwidProduct {
  id: number
  name: string
  price: number
  compareToPrice?: number
  url: string
  thumbnailUrl?: string
  description: string
  autogeneratedSlug: string
  sku: string
  originalImageUrl?: string
}

export interface ParsedProduct {
  id: number
  slug: string
  title: string
  imageURL: string
  price: string
  discountedPrice?: string
  shortDescription?: string
}
