export interface EcwidCategory {
  id: number
  orderBy: number
  name: string
  nameTranslated: Record<string, string>
  url: string
  parentId: number | null
  autogeneratedSlug: string
  customSlug: string
  productCount: number
  description: string
  descriptionTranslated: Record<string, string>
  enabled: boolean
  isSampleCategory: boolean
  seoTitle: string
  seoDescription: string
  image: string | undefined
  alt: {
    main: string
  }
}

export interface EcwidCategoriesResponse {
  total: number
  count: number
  offset: number
  limit: number
  items: EcwidCategory[]
}
