export interface EcwidCategory {
  id: number;
  orderBy: number;
  name: string;
  nameTranslated: Record<string, string>;
  url: string;
  parentId: number | null;
  autogeneratedSlug: string;
  customSlug: string;
  productCount: number;
  description: string;
  descriptionTranslated: Record<string, string>;
  enabled: boolean;
  isSampleCategory: boolean;
  seoTitle: string;
  seoDescription: string;
  image: string | undefined;
  alt: {
    main: string;
  };
}

export interface EcwidCategoriesResponse {
  total: number;
  count: number;
  offset: number;
  limit: number;
  items: EcwidCategory[];
}

export interface EcwidProduct {
  id: number;
  name: string;
  price: number;
  compareToPrice?: number;
  url: string;
  thumbnailUrl?: string;
  description: string;
  autogeneratedSlug: string;
  sku: string;
  originalImageUrl?: string;
  defaultDisplayedPrice: number;
  defaultDisplayedPriceFormatted: string;
  defaultDisplayedLowestPriceFormatted: string;
  defaultDisplayedLowestPrice: number;
}

export interface EcwidProductsResponse {
  total: number;
  count: number;
  offset: number;
  limit: number;
  items: EcwidProduct[];
}
