import { useProducts } from '@/api/productsService'
import type { EcwidProduct } from '@/types/ecwid'
import type { ProductCardItem } from '@/types/productCard'
import { defineStore } from 'pinia'
import { ref } from 'vue'
import { useCategoryStore } from './useCategoryStore'
import { parseProductCards } from '@/utils/Catalog/parseEcwidProducts.ts'

export const useProductStore = defineStore('product', () => {
  const { fetchProducts } = useProducts()

  const { getCategoryIdBySlug } = useCategoryStore()

  const products = ref<EcwidProduct[]>([])
  const allProducts = ref<EcwidProduct[]>([])
  const currentPageProducts = ref<ProductCardItem[]>([])
  const currentProduct = ref<ProductCardItem>()
  const loading = ref(false)

  async function loadProducts(currentSlug?: string): Promise<EcwidProduct[] | undefined> {
    loading.value = true
    const categoryId =
      typeof currentSlug === 'string' ? getCategoryIdBySlug(currentSlug) : undefined
    try {
      const data = await fetchProducts(categoryId)
      if ('items' in data) {
        products.value = data.items
        currentPageProducts.value = parseProductCards(data.items)
      }
      return data.items
    } catch (err) {
      console.error('Error when fetching products:', err)
      throw err
    } finally {
      loading.value = false
    }
  }

  async function loadProductBySlug(slug: string): Promise<ProductCardItem | undefined> {
    const product = products.value.find((product) => product.autogeneratedSlug === slug)
    if (product) {
      currentProduct.value = parseProductCards([product])[0]
      return currentProduct.value
    } else {
      try {
        loading.value = true
        const allProducts = await fetchProducts()
        const product = allProducts.items.find((product) => product.autogeneratedSlug === slug)
        if (product) {
          currentProduct.value = parseProductCards([product])[0]
          return currentProduct.value
        }
      } catch (err) {
        console.error('Error when fetching products:', err)
        throw err
      } finally {
        loading.value = false
      }
    }
    return
  }

  return {
    products,
    allProducts,
    currentPageProducts,
    currentProduct,
    loading,
    loadProducts,
    loadProductBySlug,
  }
})
